### ISSUE TITLE
Disabling plugin doesn't restore default opponent's deck view in HDT

### ISSUE THREAD

**Issue by jbellis** [fatheroctopus/hdt-deck-predictor#6]
Tried reinstalling HDT and it's still gone.  Is there a simple fix?

**Comment by fatheroctopus** [comment]
Yes, there's an option in HDT that shows or hides the opponent's deck, and my plugin disables that setting. I think it might be Options->Overlay->Windows->Opponent?

**Comment by jbellis** [comment]
Thanks, I found it!
