### ISSUE TITLE
Was working fine before 1st May 2020 

### ISSUE THREAD

**Issue by Illumiknight07** [fatheroctopus/hdt-deck-predictor#7]
After this new season has come out for some reason the HDT does not recognise this as a plugin and once you have put it in the plugins folder it doesn't show up in Options -> Plugins where you should be able to toggle the plugin. it is just empty there, i don't know if this is because of the season or not I'm just using it as a timestamp. 
![image](https://user-images.githubusercontent.com/30243057/80860111-889c1900-8c5d-11ea-94ea-629c3a985d33.png)

**Comment by Amy-girl** [comment]
I have been trying for an hour to make it work but I have no idea. I was going to use this to learn how to be a better player. Would really like for this to fixed

**Comment by fatheroctopus** [comment]
My guess is the HDT Plugin API has changed, I'll update this issue when I take a look at it, but just FYI I don't actively develop this mod anymore. Pull-requests are welcome!

**Comment by fatheroctopus** [comment]
FYI - the latest release hopefully addresses this issue

**Comment by Maxinho96** [comment]
Hi, I still have the same issue with the latest release.
